name: build-and-push

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*.*.*']

# Grant GITHUB_TOKEN rights to push to GHCR and upload Trivy results if you add SARIF later
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: Pick ONE canonical image name and use it everywhere.
      # If you want the package to be "simulate", keep images: ghcr.io/${{ github.repository_owner }}/simulate
      # If you'd rather match the repo, change both occurrences to .../${{ github.repository_owner }}/staffer-sims
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/simulate
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-,format=short
            type=ref,event=tag

      # Build once locally for fast Trivy scan (no push yet)
      - name: Build image for local scan
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: simulate:local
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: simulate:local
          format: 'sarif'           # SARIF format for Security tab
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # (optional) be explicit about severities
          exit-code: '1'            # fail on findings

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      # Real multi-arch build & push with the exact tags from metadata
      - name: Build and push (multi-arch)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Reduce size / avoid attestation surprises unless you want them
          provenance: false
          sbom: false

      # Optional: smoke run to verify the image is runnable
      - name: Smoke test (help)
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull $(echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | head -n1)
          docker run --rm $(echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | head -n1) --help || true

  # Notification job for failed builds
  notify:
    runs-on: ubuntu-latest
    needs: docker
    if: failure()
    steps:
      - name: Notify on failure
        run: |
          echo "❌ Docker build failed! Check the logs for details."
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
